#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -f "$OPENSHIFT_DATA_DIR"secrets.json ]; then
	echo "Generating $OPENSHIFT_DATA_DIR/secrets.json"
	python "$OPENSHIFT_REPO_DIR"libs/secrets.py > "$OPENSHIFT_DATA_DIR"secrets.json
fi

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py migrate_schemas'"
python "$OPENSHIFT_REPO_DIR"manage.py migrate_schemas

echo "Installing bower"
export HOME=$OPENSHIFT_REPO_DIR
npm install bower --prefix $OPENSHIFT_REPO_DIR
export HOME=$OPENSHIFT_HOMEDIR
export OPENSHIFT_BOWER_PATH=$OPENSHIFT_REPO_DIR/node_modules/.bin/bower

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py bower_install'"
python "$OPENSHIFT_REPO_DIR"manage.py bower_install

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py collectstatic --noinput
