# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stables_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='billing_address',
        ),
    ]
