# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stables_shop', '0002_remove_cart_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', shop.money.fields.MoneyField(help_text='How much was paid with this particular transfer.', verbose_name='Amount paid')),
                ('transaction_id', models.CharField(help_text="The transaction processor's reference", max_length=255, verbose_name='Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at')),
                ('payment_method', models.CharField(help_text='The payment backend used to process the purchase', max_length=50, verbose_name='Payment method')),
            ],
            options={
                'verbose_name': 'Order payment',
                'verbose_name_plural': 'Order payments',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address_text',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stables_shop.Order', verbose_name='Order'),
        ),
    ]
