# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stables_shop', '0003_auto_20161007_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='productactivator',
            name='order',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='activators', to='stables_shop.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productactivator',
            name='order_item',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stables_shop.OrderItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productactivator',
            name='product',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='stables_shop.Product'),
            preserve_default=False,
        ),
    ]
