# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-12 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stables_shop', '0005_product_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
